enableSecurityManager: true
enableInputThread: false
contentMd5: true
cache:
  cachedFilesExpiry: 86400
  cachedAccountsMaxItems: 1000
  cachedIncludesExpiry: 3600
  cachedIncludesMaxItems: 1000
  cachedAccountIdsExpiry: 86400
  cachedBodiesMaxItems: 1000
  cachedAccountsExpiry: 1800
  cachedFilesMaxItems: 1000
  cachedAccountIdsMaxItems: 1000
  cachedSessionsMaxItems: 1000
  enabled: true
  cachedBodiesExpiry: 3600
sessions:
  enableDb: true
  autoLoad: false
  sessionTimeout: 86400
debug: false
webAddress: localhost
templates:
  engine: !!com.github.intellectualsites.kvantum.api.config.CoreConfig$TemplatingEngine 'CRUSH'
  applyTemplates:
  - ffe9322f-56b2-491a-8230-6321daeecf4f
logPrefix: Web
gzip: true
ssl:
  port: 8000
  keyStorePassword: lol123
  enable: false
  keyStore: kvantum.jks
verbose: false
hostname: localhost
enableSyntax: true
application:
  databaseImplementation: sqlite
  main: ''
port: 80
logging:
  logFormat: '[${applicationPrefix}][${logPrefix}] ${message}'
buffer:
  in: 100000
  lineQueInitialization: 20
  out: 100000
workers: 1
mongodb:
  dbMorphia: isites
  collectionSessions: sessions
  dbSessions: isites
  uri: mongodb://localhost:27017
  enabled: false
disableViews: false
limits:
  limitRequestLines: 100
  limitPostBasicSize: 8190
  limitPostMultipartSize: 8190
  limitRequestLineSize: 8190
exitOnStop: true
middleware:
  loginRedirect: login
